### PR TITLE
Improve logging - satosa.attribute_mapping

### PR DESCRIPTION
**Pull request by sebulibah**
### All Submissions:

* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Have you added an explanation of what problem you are trying to solve with this PR?
* [ ] Have you added information on what your changes do and why you chose this as your solution?
* [ ] Have you written new tests for your changes?
* [ ] Does your submission pass tests?
* [ ] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

### CODE REVIEW

**Comment by c00kiemon5ter** [comment]
While the changes are simple, there is conflict. This is probably because your branch does not include the latest changes. Would you like to fix this?

**Comment by sebulibah** [comment]
I have fixed the conflict.

**Comment by c00kiemon5ter** [comment]
@sebulibah For some reason it seems that the tests do not run for you PRs. People reported that after the contributor created an account that started working again. Can you please create an account on https://travis-ci.org and let me know?

**Comment by sebulibah** [comment]
I have created the account.

**Pull request merged**
