### PR TITLE
[BugFix] sign_alg/digest_alg policy config patched

### PR DESCRIPTION
**Pull request by peppelinux**
This PR fixes: https://github.com/IdentityPython/SATOSA/issues/212

Now in configuration of both backend and fronted we can use both W3C format or saml2.xmldsig attr name like follows:

````
            # they works both
            # sign_alg: 'SIG_RSA_SHA384'
            # digest_alg: 'DIGEST_SHA384'
            sign_alg: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
            digest_alg: "http://www.w3.org/2001/04/xmlenc#sha256"
````

The merge would be from this specialized branch created for this patch, see diffs for better view.
"Unfortunately" this code is too much coupled with my pplnx-dev branch and in this PR wll also came a support for selectable sign and digest algs for satosa backeds, already purposed here:
https://github.com/IdentityPython/SATOSA/pull/214

Hope you like and also you need it as I needed it when I developed it

### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you added an explanation of what problem you are trying to solve with this PR?
* [x] Have you added information on what your changes do and why you chose this as your solution?
* [ ] Have you written new tests for your changes?
* [x] Does your submission pass tests?
* [x] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

### CODE REVIEW

**Comment by peppelinux** [comment]
I there any possibility to discuss this patch together and, after a good sematic refactor, merge it to the master branch? This PR is just a bugfix

**Comment by peppelinux** [comment]
@c00kiemon5ter is there any revisions on this PR?
Probably the funcion named "xmldsig_validate_w3c_format" can be modified and some other things, let me know

**Comment by peppelinux** [comment]
@c00kiemon5ter it's just a bugfix, I can refactor this as well if you start a revision.
This could be coupled with https://github.com/IdentityPython/SATOSA/pull/214/files

**Comment by c00kiemon5ter** [comment]
Also closing this. This should be handled by pysaml2 and the `signing_algorithm` and `digest_algorithm` options.

The frontend used the `sign_alg` and `digest_alg` options and we should now remove them.

---

As I noted on https://github.com/IdentityPython/SATOSA/pull/214#issuecomment-744396678 YAML and satosa are not responsible to resolve symbols.

```yaml
            # they works both
            # sign_alg: 'SIG_RSA_SHA384'   # NOT OK
            # digest_alg: 'DIGEST_SHA384'  # NOT OK
            sign_alg: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"  # OK
            digest_alg: "http://www.w3.org/2001/04/xmlenc#sha256"          # OK
```

**Pull request closed without merging**
