### PR TITLE
Dynamic saml discovery service

### PR DESCRIPTION
**Pull request by skoranda**
### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you added an explanation of what problem you are trying to solve with this PR?
* [x] Have you added information on what your changes do and why you chose this as your solution?
* [x] Have you written new tests for your changes?
* [x] Does your submission pass tests?
* [x] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

### CODE REVIEW

**Comment by peppelinux** [comment]
I read the changes, It seems an important PR. What's the difference between the previous code, can you comment the feature that come with this PR?

**Comment by skoranda** [comment]
The SAMLBackend start_auth() and disco_query() methods have been
modified so that disco_query() can check the context for the base URL
to use for the discovery service. This allows request microservices
the opportunity to set the base URL for the discovery service to use.

**Comment by skoranda** [comment]
In a request microservice one can do something like

context.decorate(SAMLBackend.KEY_SAML_DISCOVERY_SERVICE_URL, "https://my.org/disco")

**Comment by peppelinux** [comment]
Tomorrow I'll do tests, It seems to be also related to  https://github.com/IdentityPython/SATOSA/pull/220

**Pull request merged**
